import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// docs/ 配下のfolder構造からsidebarを自動生成する。
// content移植前のため、手動sidebar定義はまだ不要。
const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
